[project]
name = "dance-anonymizer"
version = "0.1.0"
description = "AI Video Dance Anonymizer and Privacy Pipeline"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "ultralytics==8.3.82",
    "onnx==1.17.0",
    "numpy>=1.24.0",
    "torch>=2.0.0",
    "torchvision>=0.15.0",
    "pillow>=9.0.0",
    "onnxscript>=0.7.1",
    "onnxruntime>=1.24.3",
    "onnxslim>=0.1.96",
    "onnxconverter-common>=1.16.0",
]

[tool.uv]
package = false
