// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


class NativeCapabilitiesDto {
  NativeCapabilitiesDto({
    required this.platform,
    required this.osVersion,
    required this.gpuSupported,
    required this.h264Encoder,
    required this.hevcEncoder,
    required this.maxEncodeWidth,
    required this.maxEncodeHeight,
    required this.cpuCores,
    required this.recommendedProfile,
    required this.supportedProfiles,
    required this.inferenceBackends,
  });

  String platform;

  String osVersion;

  bool gpuSupported;

  bool h264Encoder;

  bool hevcEncoder;

  int maxEncodeWidth;

  int maxEncodeHeight;

  int cpuCores;

  String recommendedProfile;

  List<String> supportedProfiles;

  List<String> inferenceBackends;

  List<Object?> _toList() {
    return <Object?>[
      platform,
      osVersion,
      gpuSupported,
      h264Encoder,
      hevcEncoder,
      maxEncodeWidth,
      maxEncodeHeight,
      cpuCores,
      recommendedProfile,
      supportedProfiles,
      inferenceBackends,
    ];
  }

  Object encode() {
    return _toList();  }

  static NativeCapabilitiesDto decode(Object result) {
    result as List<Object?>;
    return NativeCapabilitiesDto(
      platform: result[0]! as String,
      osVersion: result[1]! as String,
      gpuSupported: result[2]! as bool,
      h264Encoder: result[3]! as bool,
      hevcEncoder: result[4]! as bool,
      maxEncodeWidth: result[5]! as int,
      maxEncodeHeight: result[6]! as int,
      cpuCores: result[7]! as int,
      recommendedProfile: result[8]! as String,
      supportedProfiles: (result[9]! as List<Object?>).cast<String>(),
      inferenceBackends: (result[10]! as List<Object?>).cast<String>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NativeCapabilitiesDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(platform, other.platform) && _deepEquals(osVersion, other.osVersion) && _deepEquals(gpuSupported, other.gpuSupported) && _deepEquals(h264Encoder, other.h264Encoder) && _deepEquals(hevcEncoder, other.hevcEncoder) && _deepEquals(maxEncodeWidth, other.maxEncodeWidth) && _deepEquals(maxEncodeHeight, other.maxEncodeHeight) && _deepEquals(cpuCores, other.cpuCores) && _deepEquals(recommendedProfile, other.recommendedProfile) && _deepEquals(supportedProfiles, other.supportedProfiles) && _deepEquals(inferenceBackends, other.inferenceBackends);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NativeCapabilitiesDto(platform: $platform, osVersion: $osVersion, gpuSupported: $gpuSupported, h264Encoder: $h264Encoder, hevcEncoder: $hevcEncoder, maxEncodeWidth: $maxEncodeWidth, maxEncodeHeight: $maxEncodeHeight, cpuCores: $cpuCores, recommendedProfile: $recommendedProfile, supportedProfiles: $supportedProfiles, inferenceBackends: $inferenceBackends)';
  }
}

class VideoInfoDto {
  VideoInfoDto({
    required this.codedWidth,
    required this.codedHeight,
    required this.displayWidth,
    required this.displayHeight,
    required this.fps,
    required this.durationMs,
    required this.rotation,
    required this.videoCodec,
    this.audioCodec,
    required this.hasAudio,
  });

  int codedWidth;

  int codedHeight;

  int displayWidth;

  int displayHeight;

  double fps;

  int durationMs;

  int rotation;

  String videoCodec;

  String? audioCodec;

  bool hasAudio;

  List<Object?> _toList() {
    return <Object?>[
      codedWidth,
      codedHeight,
      displayWidth,
      displayHeight,
      fps,
      durationMs,
      rotation,
      videoCodec,
      audioCodec,
      hasAudio,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoInfoDto decode(Object result) {
    result as List<Object?>;
    return VideoInfoDto(
      codedWidth: result[0]! as int,
      codedHeight: result[1]! as int,
      displayWidth: result[2]! as int,
      displayHeight: result[3]! as int,
      fps: result[4]! as double,
      durationMs: result[5]! as int,
      rotation: result[6]! as int,
      videoCodec: result[7]! as String,
      audioCodec: result[8] as String?,
      hasAudio: result[9]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoInfoDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(codedWidth, other.codedWidth) && _deepEquals(codedHeight, other.codedHeight) && _deepEquals(displayWidth, other.displayWidth) && _deepEquals(displayHeight, other.displayHeight) && _deepEquals(fps, other.fps) && _deepEquals(durationMs, other.durationMs) && _deepEquals(rotation, other.rotation) && _deepEquals(videoCodec, other.videoCodec) && _deepEquals(audioCodec, other.audioCodec) && _deepEquals(hasAudio, other.hasAudio);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoInfoDto(codedWidth: $codedWidth, codedHeight: $codedHeight, displayWidth: $displayWidth, displayHeight: $displayHeight, fps: $fps, durationMs: $durationMs, rotation: $rotation, videoCodec: $videoCodec, audioCodec: $audioCodec, hasAudio: $hasAudio)';
  }
}

class DetectedPersonDto {
  DetectedPersonDto({
    required this.id,
    required this.x1,
    required this.y1,
    required this.x2,
    required this.y2,
    required this.thumbnailPath,
    required this.confidence,
  });

  int id;

  double x1;

  double y1;

  double x2;

  double y2;

  String thumbnailPath;

  double confidence;

  List<Object?> _toList() {
    return <Object?>[
      id,
      x1,
      y1,
      x2,
      y2,
      thumbnailPath,
      confidence,
    ];
  }

  Object encode() {
    return _toList();  }

  static DetectedPersonDto decode(Object result) {
    result as List<Object?>;
    return DetectedPersonDto(
      id: result[0]! as int,
      x1: result[1]! as double,
      y1: result[2]! as double,
      x2: result[3]! as double,
      y2: result[4]! as double,
      thumbnailPath: result[5]! as String,
      confidence: result[6]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! DetectedPersonDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(id, other.id) && _deepEquals(x1, other.x1) && _deepEquals(y1, other.y1) && _deepEquals(x2, other.x2) && _deepEquals(y2, other.y2) && _deepEquals(thumbnailPath, other.thumbnailPath) && _deepEquals(confidence, other.confidence);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'DetectedPersonDto(id: $id, x1: $x1, y1: $y1, x2: $x2, y2: $y2, thumbnailPath: $thumbnailPath, confidence: $confidence)';
  }
}

class AnalyzeRequestDto {
  AnalyzeRequestDto({
    required this.videoUri,
    required this.modelProfile,
  });

  String videoUri;

  String modelProfile;

  List<Object?> _toList() {
    return <Object?>[
      videoUri,
      modelProfile,
    ];
  }

  Object encode() {
    return _toList();  }

  static AnalyzeRequestDto decode(Object result) {
    result as List<Object?>;
    return AnalyzeRequestDto(
      videoUri: result[0]! as String,
      modelProfile: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AnalyzeRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(videoUri, other.videoUri) && _deepEquals(modelProfile, other.modelProfile);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AnalyzeRequestDto(videoUri: $videoUri, modelProfile: $modelProfile)';
  }
}

class AnalyzeResultDto {
  AnalyzeResultDto({
    required this.analysisCacheId,
    required this.videoInfo,
    required this.persons,
  });

  String analysisCacheId;

  VideoInfoDto videoInfo;

  List<DetectedPersonDto> persons;

  List<Object?> _toList() {
    return <Object?>[
      analysisCacheId,
      videoInfo,
      persons,
    ];
  }

  Object encode() {
    return _toList();  }

  static AnalyzeResultDto decode(Object result) {
    result as List<Object?>;
    return AnalyzeResultDto(
      analysisCacheId: result[0]! as String,
      videoInfo: result[1]! as VideoInfoDto,
      persons: (result[2]! as List<Object?>).cast<DetectedPersonDto>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AnalyzeResultDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(analysisCacheId, other.analysisCacheId) && _deepEquals(videoInfo, other.videoInfo) && _deepEquals(persons, other.persons);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AnalyzeResultDto(analysisCacheId: $analysisCacheId, videoInfo: $videoInfo, persons: $persons)';
  }
}

class EffectConfigDto {
  EffectConfigDto({
    required this.fillMode,
    required this.fillColorArgb,
    required this.borderColorArgb,
    required this.opacity,
    required this.borderWidth,
    required this.blurStrength,
    required this.faceStickerEnabled,
    this.stickerAssetId,
    required this.stickerScale,
    required this.skinWhiten,
    required this.legStretchEnabled,
    required this.legStretch,
    required this.legZoneTop,
    required this.legZoneBottom,
  });

  String fillMode;

  int fillColorArgb;

  int borderColorArgb;

  double opacity;

  double borderWidth;

  double blurStrength;

  bool faceStickerEnabled;

  String? stickerAssetId;

  double stickerScale;

  double skinWhiten;

  bool legStretchEnabled;

  double legStretch;

  double legZoneTop;

  double legZoneBottom;

  List<Object?> _toList() {
    return <Object?>[
      fillMode,
      fillColorArgb,
      borderColorArgb,
      opacity,
      borderWidth,
      blurStrength,
      faceStickerEnabled,
      stickerAssetId,
      stickerScale,
      skinWhiten,
      legStretchEnabled,
      legStretch,
      legZoneTop,
      legZoneBottom,
    ];
  }

  Object encode() {
    return _toList();  }

  static EffectConfigDto decode(Object result) {
    result as List<Object?>;
    return EffectConfigDto(
      fillMode: result[0]! as String,
      fillColorArgb: result[1]! as int,
      borderColorArgb: result[2]! as int,
      opacity: result[3]! as double,
      borderWidth: result[4]! as double,
      blurStrength: result[5]! as double,
      faceStickerEnabled: result[6]! as bool,
      stickerAssetId: result[7] as String?,
      stickerScale: result[8]! as double,
      skinWhiten: result[9]! as double,
      legStretchEnabled: result[10]! as bool,
      legStretch: result[11]! as double,
      legZoneTop: result[12]! as double,
      legZoneBottom: result[13]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! EffectConfigDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(fillMode, other.fillMode) && _deepEquals(fillColorArgb, other.fillColorArgb) && _deepEquals(borderColorArgb, other.borderColorArgb) && _deepEquals(opacity, other.opacity) && _deepEquals(borderWidth, other.borderWidth) && _deepEquals(blurStrength, other.blurStrength) && _deepEquals(faceStickerEnabled, other.faceStickerEnabled) && _deepEquals(stickerAssetId, other.stickerAssetId) && _deepEquals(stickerScale, other.stickerScale) && _deepEquals(skinWhiten, other.skinWhiten) && _deepEquals(legStretchEnabled, other.legStretchEnabled) && _deepEquals(legStretch, other.legStretch) && _deepEquals(legZoneTop, other.legZoneTop) && _deepEquals(legZoneBottom, other.legZoneBottom);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'EffectConfigDto(fillMode: $fillMode, fillColorArgb: $fillColorArgb, borderColorArgb: $borderColorArgb, opacity: $opacity, borderWidth: $borderWidth, blurStrength: $blurStrength, faceStickerEnabled: $faceStickerEnabled, stickerAssetId: $stickerAssetId, stickerScale: $stickerScale, skinWhiten: $skinWhiten, legStretchEnabled: $legStretchEnabled, legStretch: $legStretch, legZoneTop: $legZoneTop, legZoneBottom: $legZoneBottom)';
  }
}

class FollowConfigDto {
  FollowConfigDto({
    required this.enabled,
    this.targetPersonId,
    required this.zoom,
    required this.smoothFactor,
  });

  bool enabled;

  int? targetPersonId;

  double zoom;

  double smoothFactor;

  List<Object?> _toList() {
    return <Object?>[
      enabled,
      targetPersonId,
      zoom,
      smoothFactor,
    ];
  }

  Object encode() {
    return _toList();  }

  static FollowConfigDto decode(Object result) {
    result as List<Object?>;
    return FollowConfigDto(
      enabled: result[0]! as bool,
      targetPersonId: result[1] as int?,
      zoom: result[2]! as double,
      smoothFactor: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! FollowConfigDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(enabled, other.enabled) && _deepEquals(targetPersonId, other.targetPersonId) && _deepEquals(zoom, other.zoom) && _deepEquals(smoothFactor, other.smoothFactor);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'FollowConfigDto(enabled: $enabled, targetPersonId: $targetPersonId, zoom: $zoom, smoothFactor: $smoothFactor)';
  }
}

class PreviewRequestDto {
  PreviewRequestDto({
    required this.analysisCacheId,
    required this.timestampMs,
    required this.selectedPersonIds,
    required this.effects,
    required this.follow,
    this.faceOnlyPersonIds,
  });

  String analysisCacheId;

  int timestampMs;

  List<int> selectedPersonIds;

  EffectConfigDto effects;

  FollowConfigDto follow;

  List<int>? faceOnlyPersonIds;

  List<Object?> _toList() {
    return <Object?>[
      analysisCacheId,
      timestampMs,
      selectedPersonIds,
      effects,
      follow,
      faceOnlyPersonIds,
    ];
  }

  Object encode() {
    return _toList();  }

  static PreviewRequestDto decode(Object result) {
    result as List<Object?>;
    return PreviewRequestDto(
      analysisCacheId: result[0]! as String,
      timestampMs: result[1]! as int,
      selectedPersonIds: (result[2]! as List<Object?>).cast<int>(),
      effects: result[3]! as EffectConfigDto,
      follow: result[4]! as FollowConfigDto,
      faceOnlyPersonIds: (result[5] as List<Object?>?)?.cast<int>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PreviewRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(analysisCacheId, other.analysisCacheId) && _deepEquals(timestampMs, other.timestampMs) && _deepEquals(selectedPersonIds, other.selectedPersonIds) && _deepEquals(effects, other.effects) && _deepEquals(follow, other.follow) && _deepEquals(faceOnlyPersonIds, other.faceOnlyPersonIds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PreviewRequestDto(analysisCacheId: $analysisCacheId, timestampMs: $timestampMs, selectedPersonIds: $selectedPersonIds, effects: $effects, follow: $follow, faceOnlyPersonIds: $faceOnlyPersonIds)';
  }
}

class PreviewFrameDto {
  PreviewFrameDto({
    required this.thumbnailPath,
    required this.timestampMs,
    required this.renderTimeMs,
  });

  String thumbnailPath;

  int timestampMs;

  double renderTimeMs;

  List<Object?> _toList() {
    return <Object?>[
      thumbnailPath,
      timestampMs,
      renderTimeMs,
    ];
  }

  Object encode() {
    return _toList();  }

  static PreviewFrameDto decode(Object result) {
    result as List<Object?>;
    return PreviewFrameDto(
      thumbnailPath: result[0]! as String,
      timestampMs: result[1]! as int,
      renderTimeMs: result[2]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! PreviewFrameDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(thumbnailPath, other.thumbnailPath) && _deepEquals(timestampMs, other.timestampMs) && _deepEquals(renderTimeMs, other.renderTimeMs);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'PreviewFrameDto(thumbnailPath: $thumbnailPath, timestampMs: $timestampMs, renderTimeMs: $renderTimeMs)';
  }
}

class ExportRequestDto {
  ExportRequestDto({
    required this.sourceUri,
    required this.analysisCacheId,
    required this.outputFilePath,
    required this.selectedPersonIds,
    required this.effects,
    required this.follow,
    required this.targetWidth,
    required this.targetHeight,
    required this.targetFps,
    required this.videoBitrate,
    required this.processingProfile,
    required this.enableLivePreview,
    this.faceOnlyPersonIds,
  });

  String sourceUri;

  String analysisCacheId;

  String outputFilePath;

  List<int> selectedPersonIds;

  EffectConfigDto effects;

  FollowConfigDto follow;

  int targetWidth;

  int targetHeight;

  double targetFps;

  int videoBitrate;

  String processingProfile;

  bool enableLivePreview;

  List<int>? faceOnlyPersonIds;

  List<Object?> _toList() {
    return <Object?>[
      sourceUri,
      analysisCacheId,
      outputFilePath,
      selectedPersonIds,
      effects,
      follow,
      targetWidth,
      targetHeight,
      targetFps,
      videoBitrate,
      processingProfile,
      enableLivePreview,
      faceOnlyPersonIds,
    ];
  }

  Object encode() {
    return _toList();  }

  static ExportRequestDto decode(Object result) {
    result as List<Object?>;
    return ExportRequestDto(
      sourceUri: result[0]! as String,
      analysisCacheId: result[1]! as String,
      outputFilePath: result[2]! as String,
      selectedPersonIds: (result[3]! as List<Object?>).cast<int>(),
      effects: result[4]! as EffectConfigDto,
      follow: result[5]! as FollowConfigDto,
      targetWidth: result[6]! as int,
      targetHeight: result[7]! as int,
      targetFps: result[8]! as double,
      videoBitrate: result[9]! as int,
      processingProfile: result[10]! as String,
      enableLivePreview: result[11]! as bool,
      faceOnlyPersonIds: (result[12] as List<Object?>?)?.cast<int>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ExportRequestDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sourceUri, other.sourceUri) && _deepEquals(analysisCacheId, other.analysisCacheId) && _deepEquals(outputFilePath, other.outputFilePath) && _deepEquals(selectedPersonIds, other.selectedPersonIds) && _deepEquals(effects, other.effects) && _deepEquals(follow, other.follow) && _deepEquals(targetWidth, other.targetWidth) && _deepEquals(targetHeight, other.targetHeight) && _deepEquals(targetFps, other.targetFps) && _deepEquals(videoBitrate, other.videoBitrate) && _deepEquals(processingProfile, other.processingProfile) && _deepEquals(enableLivePreview, other.enableLivePreview) && _deepEquals(faceOnlyPersonIds, other.faceOnlyPersonIds);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ExportRequestDto(sourceUri: $sourceUri, analysisCacheId: $analysisCacheId, outputFilePath: $outputFilePath, selectedPersonIds: $selectedPersonIds, effects: $effects, follow: $follow, targetWidth: $targetWidth, targetHeight: $targetHeight, targetFps: $targetFps, videoBitrate: $videoBitrate, processingProfile: $processingProfile, enableLivePreview: $enableLivePreview, faceOnlyPersonIds: $faceOnlyPersonIds)';
  }
}

class JobStatusDto {
  JobStatusDto({
    required this.jobId,
    required this.state,
    required this.currentFrame,
    required this.totalFrames,
    required this.fps,
    required this.progress,
    this.outputUri,
    this.currentPreviewPath,
    this.errorCode,
    this.errorMessage,
  });

  String jobId;

  String state;

  int currentFrame;

  int totalFrames;

  double fps;

  double progress;

  String? outputUri;

  String? currentPreviewPath;

  String? errorCode;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      jobId,
      state,
      currentFrame,
      totalFrames,
      fps,
      progress,
      outputUri,
      currentPreviewPath,
      errorCode,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static JobStatusDto decode(Object result) {
    result as List<Object?>;
    return JobStatusDto(
      jobId: result[0]! as String,
      state: result[1]! as String,
      currentFrame: result[2]! as int,
      totalFrames: result[3]! as int,
      fps: result[4]! as double,
      progress: result[5]! as double,
      outputUri: result[6] as String?,
      currentPreviewPath: result[7] as String?,
      errorCode: result[8] as String?,
      errorMessage: result[9] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! JobStatusDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(jobId, other.jobId) && _deepEquals(state, other.state) && _deepEquals(currentFrame, other.currentFrame) && _deepEquals(totalFrames, other.totalFrames) && _deepEquals(fps, other.fps) && _deepEquals(progress, other.progress) && _deepEquals(outputUri, other.outputUri) && _deepEquals(currentPreviewPath, other.currentPreviewPath) && _deepEquals(errorCode, other.errorCode) && _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'JobStatusDto(jobId: $jobId, state: $state, currentFrame: $currentFrame, totalFrames: $totalFrames, fps: $fps, progress: $progress, outputUri: $outputUri, currentPreviewPath: $currentPreviewPath, errorCode: $errorCode, errorMessage: $errorMessage)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is NativeCapabilitiesDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    }    else if (value is VideoInfoDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    }    else if (value is DetectedPersonDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is AnalyzeRequestDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is AnalyzeResultDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is EffectConfigDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is FollowConfigDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is PreviewRequestDto) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is PreviewFrameDto) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is ExportRequestDto) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is JobStatusDto) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        return NativeCapabilitiesDto.decode(readValue(buffer)!);
      case 130:
        return VideoInfoDto.decode(readValue(buffer)!);
      case 131:
        return DetectedPersonDto.decode(readValue(buffer)!);
      case 132:
        return AnalyzeRequestDto.decode(readValue(buffer)!);
      case 133:
        return AnalyzeResultDto.decode(readValue(buffer)!);
      case 134:
        return EffectConfigDto.decode(readValue(buffer)!);
      case 135:
        return FollowConfigDto.decode(readValue(buffer)!);
      case 136:
        return PreviewRequestDto.decode(readValue(buffer)!);
      case 137:
        return PreviewFrameDto.decode(readValue(buffer)!);
      case 138:
        return ExportRequestDto.decode(readValue(buffer)!);
      case 139:
        return JobStatusDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class DanceNativeApi {
  /// Constructor for [DanceNativeApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  DanceNativeApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  Future<NativeCapabilitiesDto> getCapabilities() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.dance_native.DanceNativeApi.getCapabilities$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as NativeCapabilitiesDto;
  }

  Future<VideoInfoDto> probeVideo(String uri) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.dance_native.DanceNativeApi.probeVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[uri]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as VideoInfoDto;
  }

  Future<AnalyzeResultDto> analyzeVideo(AnalyzeRequestDto request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.dance_native.DanceNativeApi.analyzeVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as AnalyzeResultDto;
  }

  Future<PreviewFrameDto> getPreviewFrame(PreviewRequestDto request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.dance_native.DanceNativeApi.getPreviewFrame$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as PreviewFrameDto;
  }

  Future<String> startExport(ExportRequestDto request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.dance_native.DanceNativeApi.startExport$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<void> cancelJob(String jobId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.dance_native.DanceNativeApi.cancelJob$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[jobId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<JobStatusDto> getJobStatus(String jobId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.dance_native.DanceNativeApi.getJobStatus$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[jobId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as JobStatusDto;
  }

  Future<void> releaseProject(String projectId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.dance_native.DanceNativeApi.releaseProject$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[projectId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class DanceProcessingEvents {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onProgressUpdate(JobStatusDto status);

  static void setUp(DanceProcessingEvents? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.dance_native.DanceProcessingEvents.onProgressUpdate$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final JobStatusDto arg_status = args[0]! as JobStatusDto;
          try {
            api.onProgressUpdate(arg_status);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
