#!/usr/bin/env python3
"""GitHub macOS Phase 7 gate for Release-shaped iOS pre-release readiness."""

from __future__ import annotations

import os
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
APP = ROOT / "mobile/app"
PHASE7_XCCONFIG = APP / "ios/Flutter/Phase7Release.xcconfig"
ARTIFACTS = APP / "artifacts"


def annotation_escape(value: str) -> str:
    return value.replace("%", "%25").replace("\r", "%0D").replace("\n", "%0A")


def run(
    command: list[str],
    *,
    cwd: Path = ROOT,
    timeout: int = 1800,
    env_overrides: dict[str, str] | None = None,
) -> None:
    rendered = " ".join(command)
    print("+", rendered, flush=True)
    environment = os.environ.copy()
    if env_overrides:
        environment.update(env_overrides)
    try:
        completed = subprocess.run(
            command,
            cwd=cwd,
            check=False,
            timeout=timeout,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            env=environment,
        )
    except subprocess.TimeoutExpired as exc:
        tail = (exc.stdout or "")[-8000:]
        print(tail, end="" if tail.endswith("\n") else "\n")
        print(
            "::error title=Woah Phase 7 macOS gate timeout::"
            + annotation_escape(f"{rendered} timed out after {timeout}s\n{tail}")
        )
        raise

    output = completed.stdout or ""
    if output:
        print(output, end="" if output.endswith("\n") else "\n")
    if completed.returncode != 0:
        tail = output[-8000:]
        print(
            "::error title=Woah Phase 7 macOS gate failed::"
            + annotation_escape(f"command={rendered}\nexit={completed.returncode}\n{tail}")
        )
        raise SystemExit(completed.returncode)


def head() -> str:
    completed = subprocess.run(
        ["git", "rev-parse", "HEAD"],
        cwd=ROOT,
        check=True,
        text=True,
        stdout=subprocess.PIPE,
    )
    return completed.stdout.strip()


def write_release_identity(commit: str, *, enable_smoke_hooks: bool) -> None:
    smoke_value = "YES" if enable_smoke_hooks else "NO"
    PHASE7_XCCONFIG.write_text(
        "// Generated by run_phase7_macos_gate.py; intentionally ignored.\n"
        f"WOAH_GIT_COMMIT = {commit}\n"
        f"WOAH_ENABLE_SMOKE_HOOKS = {smoke_value}\n",
        encoding="utf-8",
    )


def main() -> int:
    if sys.platform != "darwin":
        raise SystemExit("Phase 7 macOS gate must run on macOS")

    for phase in range(0, 8):
        # Phase 1 owns the legacy GitHub hook that launches the strongest
        # accepted Phase 6 Apple gate. Phase 7 invokes that gate explicitly
        # immediately below, so suppress only the inherited auto-hook for this
        # static-verifier subprocess to avoid executing the same expensive
        # Simulator/Metal/media lane twice. The Phase 1 static contract itself
        # still runs unchanged.
        overrides = {"GITHUB_ACTIONS": "false"} if phase == 1 else None
        run(
            [sys.executable, f"tools/release/verify_ios_phase{phase}.py"],
            env_overrides=overrides,
        )

    # Phase 7 is release readiness, not a replacement for prior deterministic
    # evidence. Re-run the strongest accepted Phase 6 lane first.
    run([sys.executable, "tools/ios/run_phase6_macos_gate.py"], timeout=2700)

    # A release artifact without the production model is not release-ready.
    # The workflow provisions the canonical source model before this gate.
    run([sys.executable, "tools/release/sync_ios_yolo_model.py", "--verify-only"])
    run(
        [sys.executable, "tools/release/verify_ios_phase1.py", "--require-model"],
        env_overrides={"GITHUB_ACTIONS": "false"},
    )

    commit = head()
    ARTIFACTS.mkdir(parents=True, exist_ok=True)

    run(["flutter", "config", "--enable-swift-package-manager"], cwd=APP)
    run(["flutter", "pub", "get", "--enforce-lockfile"], cwd=APP)

    # Flutter does not ship a Release engine for iOS Simulator. Re-run the
    # complete Phase 3-6 stack plus the Phase 7-owned real-media regressions on
    # a Debug Simulator for Apple-runtime evidence. Release compilation remains
    # a separate iPhoneOS no-codesign gate below.
    run(
        [
            "flutter",
            "build",
            "ios",
            "--simulator",
            "--debug",
            "--target",
            "lib/ios_phase7_smoke_main.dart",
        ],
        cwd=APP,
        timeout=2400,
    )
    run(
        [
            sys.executable,
            "tools/ios/run_phase7_simulator_smoke.py",
            "--app",
            "mobile/app/build/ios/iphonesimulator/Runner.app",
        ],
        timeout=1500,
    )

    # Build the actual production entrypoint for Simulator and require a short
    # launch/liveness smoke. This is still Debug-mode runtime evidence because
    # Flutter does not support Release mode on Simulator; it must not be used as
    # evidence that Release smoke hooks are disabled.
    run(
        [
            "flutter",
            "build",
            "ios",
            "--simulator",
            "--debug",
            "--target",
            "lib/main.dart",
        ],
        cwd=APP,
        timeout=1800,
    )
    run(
        [
            sys.executable,
            "tools/ios/run_phase7_production_simulator_smoke.py",
            "--app",
            "mobile/app/build/ios/iphonesimulator/Runner.app",
        ],
        timeout=900,
    )

    # The real production artifact is built for iPhoneOS Release. Release.xcconfig
    # defaults smoke hooks to NO, and the generated identity explicitly keeps
    # that fail-closed value before the audited no-codesign build.
    write_release_identity(commit, enable_smoke_hooks=False)
    run(
        [
            "flutter",
            "build",
            "ios",
            "--release",
            "--no-codesign",
            "--target",
            "lib/main.dart",
        ],
        cwd=APP,
        timeout=2400,
    )
    release_app = APP / "build/ios/iphoneos/Runner.app"
    audit = ARTIFACTS / "phase7_release_audit.json"
    archive = ARTIFACTS / "Woah-ios-release-app.zip"
    run(
        [
            sys.executable,
            "tools/ios/audit_phase7_release_bundle.py",
            "--app",
            str(release_app),
            "--output",
            str(audit),
        ]
    )
    if archive.exists():
        archive.unlink()
    run(
        [
            "/usr/bin/ditto",
            "-c",
            "-k",
            "--sequesterRsrc",
            "--keepParent",
            str(release_app),
            str(archive),
        ]
    )
    print(f"IOS_PHASE7_RELEASE_ARCHIVE={archive}")
    print("IOS_PHASE7_MACOS_GATE=PASS")
    print("IOS_PHASE7_STATUS=implementation complete pending physical-device acceptance")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

