// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum DanceApiPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Generated class from Pigeon that represents data sent in messages.
struct NativeCapabilitiesDto: Hashable, CustomStringConvertible {
  var platform: String
  var osVersion: String
  var gpuSupported: Bool
  var h264Encoder: Bool
  var hevcEncoder: Bool
  var maxEncodeWidth: Int64
  var maxEncodeHeight: Int64
  var cpuCores: Int64
  var recommendedProfile: String
  var supportedProfiles: [String]
  var inferenceBackends: [String]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NativeCapabilitiesDto? {
    let platform = pigeonVar_list[0] as! String
    let osVersion = pigeonVar_list[1] as! String
    let gpuSupported = pigeonVar_list[2] as! Bool
    let h264Encoder = pigeonVar_list[3] as! Bool
    let hevcEncoder = pigeonVar_list[4] as! Bool
    let maxEncodeWidth = pigeonVar_list[5] as! Int64
    let maxEncodeHeight = pigeonVar_list[6] as! Int64
    let cpuCores = pigeonVar_list[7] as! Int64
    let recommendedProfile = pigeonVar_list[8] as! String
    let supportedProfiles = pigeonVar_list[9] as! [String]
    let inferenceBackends = pigeonVar_list[10] as! [String]

    return NativeCapabilitiesDto(
      platform: platform,
      osVersion: osVersion,
      gpuSupported: gpuSupported,
      h264Encoder: h264Encoder,
      hevcEncoder: hevcEncoder,
      maxEncodeWidth: maxEncodeWidth,
      maxEncodeHeight: maxEncodeHeight,
      cpuCores: cpuCores,
      recommendedProfile: recommendedProfile,
      supportedProfiles: supportedProfiles,
      inferenceBackends: inferenceBackends
    )
  }
  func toList() -> [Any?] {
    return [
      platform,
      osVersion,
      gpuSupported,
      h264Encoder,
      hevcEncoder,
      maxEncodeWidth,
      maxEncodeHeight,
      cpuCores,
      recommendedProfile,
      supportedProfiles,
      inferenceBackends,
    ]
  }
  static func == (lhs: NativeCapabilitiesDto, rhs: NativeCapabilitiesDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DanceApiPigeonInternal.deepEquals(lhs.platform, rhs.platform) && DanceApiPigeonInternal.deepEquals(lhs.osVersion, rhs.osVersion) && DanceApiPigeonInternal.deepEquals(lhs.gpuSupported, rhs.gpuSupported) && DanceApiPigeonInternal.deepEquals(lhs.h264Encoder, rhs.h264Encoder) && DanceApiPigeonInternal.deepEquals(lhs.hevcEncoder, rhs.hevcEncoder) && DanceApiPigeonInternal.deepEquals(lhs.maxEncodeWidth, rhs.maxEncodeWidth) && DanceApiPigeonInternal.deepEquals(lhs.maxEncodeHeight, rhs.maxEncodeHeight) && DanceApiPigeonInternal.deepEquals(lhs.cpuCores, rhs.cpuCores) && DanceApiPigeonInternal.deepEquals(lhs.recommendedProfile, rhs.recommendedProfile) && DanceApiPigeonInternal.deepEquals(lhs.supportedProfiles, rhs.supportedProfiles) && DanceApiPigeonInternal.deepEquals(lhs.inferenceBackends, rhs.inferenceBackends)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NativeCapabilitiesDto")
    DanceApiPigeonInternal.deepHash(value: platform, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: osVersion, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: gpuSupported, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: h264Encoder, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: hevcEncoder, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: maxEncodeWidth, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: maxEncodeHeight, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: cpuCores, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: recommendedProfile, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: supportedProfiles, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: inferenceBackends, hasher: &hasher)
  }

  public var description: String {
    return "NativeCapabilitiesDto(platform: \(String(describing: platform)), osVersion: \(String(describing: osVersion)), gpuSupported: \(String(describing: gpuSupported)), h264Encoder: \(String(describing: h264Encoder)), hevcEncoder: \(String(describing: hevcEncoder)), maxEncodeWidth: \(String(describing: maxEncodeWidth)), maxEncodeHeight: \(String(describing: maxEncodeHeight)), cpuCores: \(String(describing: cpuCores)), recommendedProfile: \(String(describing: recommendedProfile)), supportedProfiles: \(String(describing: supportedProfiles)), inferenceBackends: \(String(describing: inferenceBackends)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoInfoDto: Hashable, CustomStringConvertible {
  var codedWidth: Int64
  var codedHeight: Int64
  var displayWidth: Int64
  var displayHeight: Int64
  var fps: Double
  var durationMs: Int64
  var rotation: Int64
  var videoCodec: String
  var audioCodec: String? = nil
  var hasAudio: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoInfoDto? {
    let codedWidth = pigeonVar_list[0] as! Int64
    let codedHeight = pigeonVar_list[1] as! Int64
    let displayWidth = pigeonVar_list[2] as! Int64
    let displayHeight = pigeonVar_list[3] as! Int64
    let fps = pigeonVar_list[4] as! Double
    let durationMs = pigeonVar_list[5] as! Int64
    let rotation = pigeonVar_list[6] as! Int64
    let videoCodec = pigeonVar_list[7] as! String
    let audioCodec: String? = nilOrValue(pigeonVar_list[8])
    let hasAudio = pigeonVar_list[9] as! Bool

    return VideoInfoDto(
      codedWidth: codedWidth,
      codedHeight: codedHeight,
      displayWidth: displayWidth,
      displayHeight: displayHeight,
      fps: fps,
      durationMs: durationMs,
      rotation: rotation,
      videoCodec: videoCodec,
      audioCodec: audioCodec,
      hasAudio: hasAudio
    )
  }
  func toList() -> [Any?] {
    return [
      codedWidth,
      codedHeight,
      displayWidth,
      displayHeight,
      fps,
      durationMs,
      rotation,
      videoCodec,
      audioCodec,
      hasAudio,
    ]
  }
  static func == (lhs: VideoInfoDto, rhs: VideoInfoDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DanceApiPigeonInternal.deepEquals(lhs.codedWidth, rhs.codedWidth) && DanceApiPigeonInternal.deepEquals(lhs.codedHeight, rhs.codedHeight) && DanceApiPigeonInternal.deepEquals(lhs.displayWidth, rhs.displayWidth) && DanceApiPigeonInternal.deepEquals(lhs.displayHeight, rhs.displayHeight) && DanceApiPigeonInternal.deepEquals(lhs.fps, rhs.fps) && DanceApiPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && DanceApiPigeonInternal.deepEquals(lhs.rotation, rhs.rotation) && DanceApiPigeonInternal.deepEquals(lhs.videoCodec, rhs.videoCodec) && DanceApiPigeonInternal.deepEquals(lhs.audioCodec, rhs.audioCodec) && DanceApiPigeonInternal.deepEquals(lhs.hasAudio, rhs.hasAudio)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoInfoDto")
    DanceApiPigeonInternal.deepHash(value: codedWidth, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: codedHeight, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: displayWidth, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: displayHeight, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: fps, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: rotation, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: videoCodec, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: audioCodec, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: hasAudio, hasher: &hasher)
  }

  public var description: String {
    return "VideoInfoDto(codedWidth: \(String(describing: codedWidth)), codedHeight: \(String(describing: codedHeight)), displayWidth: \(String(describing: displayWidth)), displayHeight: \(String(describing: displayHeight)), fps: \(String(describing: fps)), durationMs: \(String(describing: durationMs)), rotation: \(String(describing: rotation)), videoCodec: \(String(describing: videoCodec)), audioCodec: \(String(describing: audioCodec)), hasAudio: \(String(describing: hasAudio)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct DetectedPersonDto: Hashable, CustomStringConvertible {
  var id: Int64
  var x1: Double
  var y1: Double
  var x2: Double
  var y2: Double
  var thumbnailPath: String
  var confidence: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> DetectedPersonDto? {
    let id = pigeonVar_list[0] as! Int64
    let x1 = pigeonVar_list[1] as! Double
    let y1 = pigeonVar_list[2] as! Double
    let x2 = pigeonVar_list[3] as! Double
    let y2 = pigeonVar_list[4] as! Double
    let thumbnailPath = pigeonVar_list[5] as! String
    let confidence = pigeonVar_list[6] as! Double

    return DetectedPersonDto(
      id: id,
      x1: x1,
      y1: y1,
      x2: x2,
      y2: y2,
      thumbnailPath: thumbnailPath,
      confidence: confidence
    )
  }
  func toList() -> [Any?] {
    return [
      id,
      x1,
      y1,
      x2,
      y2,
      thumbnailPath,
      confidence,
    ]
  }
  static func == (lhs: DetectedPersonDto, rhs: DetectedPersonDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DanceApiPigeonInternal.deepEquals(lhs.id, rhs.id) && DanceApiPigeonInternal.deepEquals(lhs.x1, rhs.x1) && DanceApiPigeonInternal.deepEquals(lhs.y1, rhs.y1) && DanceApiPigeonInternal.deepEquals(lhs.x2, rhs.x2) && DanceApiPigeonInternal.deepEquals(lhs.y2, rhs.y2) && DanceApiPigeonInternal.deepEquals(lhs.thumbnailPath, rhs.thumbnailPath) && DanceApiPigeonInternal.deepEquals(lhs.confidence, rhs.confidence)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("DetectedPersonDto")
    DanceApiPigeonInternal.deepHash(value: id, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: x1, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: y1, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: x2, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: y2, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: thumbnailPath, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: confidence, hasher: &hasher)
  }

  public var description: String {
    return "DetectedPersonDto(id: \(String(describing: id)), x1: \(String(describing: x1)), y1: \(String(describing: y1)), x2: \(String(describing: x2)), y2: \(String(describing: y2)), thumbnailPath: \(String(describing: thumbnailPath)), confidence: \(String(describing: confidence)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AnalyzeRequestDto: Hashable, CustomStringConvertible {
  var videoUri: String
  var modelProfile: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnalyzeRequestDto? {
    let videoUri = pigeonVar_list[0] as! String
    let modelProfile = pigeonVar_list[1] as! String

    return AnalyzeRequestDto(
      videoUri: videoUri,
      modelProfile: modelProfile
    )
  }
  func toList() -> [Any?] {
    return [
      videoUri,
      modelProfile,
    ]
  }
  static func == (lhs: AnalyzeRequestDto, rhs: AnalyzeRequestDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DanceApiPigeonInternal.deepEquals(lhs.videoUri, rhs.videoUri) && DanceApiPigeonInternal.deepEquals(lhs.modelProfile, rhs.modelProfile)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AnalyzeRequestDto")
    DanceApiPigeonInternal.deepHash(value: videoUri, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: modelProfile, hasher: &hasher)
  }

  public var description: String {
    return "AnalyzeRequestDto(videoUri: \(String(describing: videoUri)), modelProfile: \(String(describing: modelProfile)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct AnalyzeResultDto: Hashable, CustomStringConvertible {
  var analysisCacheId: String
  var videoInfo: VideoInfoDto
  var persons: [DetectedPersonDto]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnalyzeResultDto? {
    let analysisCacheId = pigeonVar_list[0] as! String
    let videoInfo = pigeonVar_list[1] as! VideoInfoDto
    let persons = pigeonVar_list[2] as! [DetectedPersonDto]

    return AnalyzeResultDto(
      analysisCacheId: analysisCacheId,
      videoInfo: videoInfo,
      persons: persons
    )
  }
  func toList() -> [Any?] {
    return [
      analysisCacheId,
      videoInfo,
      persons,
    ]
  }
  static func == (lhs: AnalyzeResultDto, rhs: AnalyzeResultDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DanceApiPigeonInternal.deepEquals(lhs.analysisCacheId, rhs.analysisCacheId) && DanceApiPigeonInternal.deepEquals(lhs.videoInfo, rhs.videoInfo) && DanceApiPigeonInternal.deepEquals(lhs.persons, rhs.persons)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AnalyzeResultDto")
    DanceApiPigeonInternal.deepHash(value: analysisCacheId, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: videoInfo, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: persons, hasher: &hasher)
  }

  public var description: String {
    return "AnalyzeResultDto(analysisCacheId: \(String(describing: analysisCacheId)), videoInfo: \(String(describing: videoInfo)), persons: \(String(describing: persons)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct EffectConfigDto: Hashable, CustomStringConvertible {
  var fillMode: String
  var fillColorArgb: Int64
  var borderColorArgb: Int64
  var opacity: Double
  var borderWidth: Double
  var blurStrength: Double
  var faceStickerEnabled: Bool
  var stickerAssetId: String? = nil
  var stickerScale: Double
  var skinWhiten: Double
  var legStretchEnabled: Bool
  var legStretch: Double
  var legZoneTop: Double
  var legZoneBottom: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> EffectConfigDto? {
    let fillMode = pigeonVar_list[0] as! String
    let fillColorArgb = pigeonVar_list[1] as! Int64
    let borderColorArgb = pigeonVar_list[2] as! Int64
    let opacity = pigeonVar_list[3] as! Double
    let borderWidth = pigeonVar_list[4] as! Double
    let blurStrength = pigeonVar_list[5] as! Double
    let faceStickerEnabled = pigeonVar_list[6] as! Bool
    let stickerAssetId: String? = nilOrValue(pigeonVar_list[7])
    let stickerScale = pigeonVar_list[8] as! Double
    let skinWhiten = pigeonVar_list[9] as! Double
    let legStretchEnabled = pigeonVar_list[10] as! Bool
    let legStretch = pigeonVar_list[11] as! Double
    let legZoneTop = pigeonVar_list[12] as! Double
    let legZoneBottom = pigeonVar_list[13] as! Double

    return EffectConfigDto(
      fillMode: fillMode,
      fillColorArgb: fillColorArgb,
      borderColorArgb: borderColorArgb,
      opacity: opacity,
      borderWidth: borderWidth,
      blurStrength: blurStrength,
      faceStickerEnabled: faceStickerEnabled,
      stickerAssetId: stickerAssetId,
      stickerScale: stickerScale,
      skinWhiten: skinWhiten,
      legStretchEnabled: legStretchEnabled,
      legStretch: legStretch,
      legZoneTop: legZoneTop,
      legZoneBottom: legZoneBottom
    )
  }
  func toList() -> [Any?] {
    return [
      fillMode,
      fillColorArgb,
      borderColorArgb,
      opacity,
      borderWidth,
      blurStrength,
      faceStickerEnabled,
      stickerAssetId,
      stickerScale,
      skinWhiten,
      legStretchEnabled,
      legStretch,
      legZoneTop,
      legZoneBottom,
    ]
  }
  static func == (lhs: EffectConfigDto, rhs: EffectConfigDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DanceApiPigeonInternal.deepEquals(lhs.fillMode, rhs.fillMode) && DanceApiPigeonInternal.deepEquals(lhs.fillColorArgb, rhs.fillColorArgb) && DanceApiPigeonInternal.deepEquals(lhs.borderColorArgb, rhs.borderColorArgb) && DanceApiPigeonInternal.deepEquals(lhs.opacity, rhs.opacity) && DanceApiPigeonInternal.deepEquals(lhs.borderWidth, rhs.borderWidth) && DanceApiPigeonInternal.deepEquals(lhs.blurStrength, rhs.blurStrength) && DanceApiPigeonInternal.deepEquals(lhs.faceStickerEnabled, rhs.faceStickerEnabled) && DanceApiPigeonInternal.deepEquals(lhs.stickerAssetId, rhs.stickerAssetId) && DanceApiPigeonInternal.deepEquals(lhs.stickerScale, rhs.stickerScale) && DanceApiPigeonInternal.deepEquals(lhs.skinWhiten, rhs.skinWhiten) && DanceApiPigeonInternal.deepEquals(lhs.legStretchEnabled, rhs.legStretchEnabled) && DanceApiPigeonInternal.deepEquals(lhs.legStretch, rhs.legStretch) && DanceApiPigeonInternal.deepEquals(lhs.legZoneTop, rhs.legZoneTop) && DanceApiPigeonInternal.deepEquals(lhs.legZoneBottom, rhs.legZoneBottom)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("EffectConfigDto")
    DanceApiPigeonInternal.deepHash(value: fillMode, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: fillColorArgb, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: borderColorArgb, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: opacity, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: borderWidth, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: blurStrength, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: faceStickerEnabled, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: stickerAssetId, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: stickerScale, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: skinWhiten, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: legStretchEnabled, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: legStretch, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: legZoneTop, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: legZoneBottom, hasher: &hasher)
  }

  public var description: String {
    return "EffectConfigDto(fillMode: \(String(describing: fillMode)), fillColorArgb: \(String(describing: fillColorArgb)), borderColorArgb: \(String(describing: borderColorArgb)), opacity: \(String(describing: opacity)), borderWidth: \(String(describing: borderWidth)), blurStrength: \(String(describing: blurStrength)), faceStickerEnabled: \(String(describing: faceStickerEnabled)), stickerAssetId: \(String(describing: stickerAssetId)), stickerScale: \(String(describing: stickerScale)), skinWhiten: \(String(describing: skinWhiten)), legStretchEnabled: \(String(describing: legStretchEnabled)), legStretch: \(String(describing: legStretch)), legZoneTop: \(String(describing: legZoneTop)), legZoneBottom: \(String(describing: legZoneBottom)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct FollowConfigDto: Hashable, CustomStringConvertible {
  var enabled: Bool
  var targetPersonId: Int64? = nil
  var zoom: Double
  var smoothFactor: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> FollowConfigDto? {
    let enabled = pigeonVar_list[0] as! Bool
    let targetPersonId: Int64? = nilOrValue(pigeonVar_list[1])
    let zoom = pigeonVar_list[2] as! Double
    let smoothFactor = pigeonVar_list[3] as! Double

    return FollowConfigDto(
      enabled: enabled,
      targetPersonId: targetPersonId,
      zoom: zoom,
      smoothFactor: smoothFactor
    )
  }
  func toList() -> [Any?] {
    return [
      enabled,
      targetPersonId,
      zoom,
      smoothFactor,
    ]
  }
  static func == (lhs: FollowConfigDto, rhs: FollowConfigDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DanceApiPigeonInternal.deepEquals(lhs.enabled, rhs.enabled) && DanceApiPigeonInternal.deepEquals(lhs.targetPersonId, rhs.targetPersonId) && DanceApiPigeonInternal.deepEquals(lhs.zoom, rhs.zoom) && DanceApiPigeonInternal.deepEquals(lhs.smoothFactor, rhs.smoothFactor)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("FollowConfigDto")
    DanceApiPigeonInternal.deepHash(value: enabled, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: targetPersonId, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: zoom, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: smoothFactor, hasher: &hasher)
  }

  public var description: String {
    return "FollowConfigDto(enabled: \(String(describing: enabled)), targetPersonId: \(String(describing: targetPersonId)), zoom: \(String(describing: zoom)), smoothFactor: \(String(describing: smoothFactor)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PreviewRequestDto: Hashable, CustomStringConvertible {
  var analysisCacheId: String
  var timestampMs: Int64
  var selectedPersonIds: [Int64]
  var effects: EffectConfigDto
  var follow: FollowConfigDto


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PreviewRequestDto? {
    let analysisCacheId = pigeonVar_list[0] as! String
    let timestampMs = pigeonVar_list[1] as! Int64
    let selectedPersonIds = pigeonVar_list[2] as! [Int64]
    let effects = pigeonVar_list[3] as! EffectConfigDto
    let follow = pigeonVar_list[4] as! FollowConfigDto

    return PreviewRequestDto(
      analysisCacheId: analysisCacheId,
      timestampMs: timestampMs,
      selectedPersonIds: selectedPersonIds,
      effects: effects,
      follow: follow
    )
  }
  func toList() -> [Any?] {
    return [
      analysisCacheId,
      timestampMs,
      selectedPersonIds,
      effects,
      follow,
    ]
  }
  static func == (lhs: PreviewRequestDto, rhs: PreviewRequestDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DanceApiPigeonInternal.deepEquals(lhs.analysisCacheId, rhs.analysisCacheId) && DanceApiPigeonInternal.deepEquals(lhs.timestampMs, rhs.timestampMs) && DanceApiPigeonInternal.deepEquals(lhs.selectedPersonIds, rhs.selectedPersonIds) && DanceApiPigeonInternal.deepEquals(lhs.effects, rhs.effects) && DanceApiPigeonInternal.deepEquals(lhs.follow, rhs.follow)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PreviewRequestDto")
    DanceApiPigeonInternal.deepHash(value: analysisCacheId, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: timestampMs, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: selectedPersonIds, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: effects, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: follow, hasher: &hasher)
  }

  public var description: String {
    return "PreviewRequestDto(analysisCacheId: \(String(describing: analysisCacheId)), timestampMs: \(String(describing: timestampMs)), selectedPersonIds: \(String(describing: selectedPersonIds)), effects: \(String(describing: effects)), follow: \(String(describing: follow)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PreviewFrameDto: Hashable, CustomStringConvertible {
  var thumbnailPath: String
  var timestampMs: Int64
  var renderTimeMs: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> PreviewFrameDto? {
    let thumbnailPath = pigeonVar_list[0] as! String
    let timestampMs = pigeonVar_list[1] as! Int64
    let renderTimeMs = pigeonVar_list[2] as! Double

    return PreviewFrameDto(
      thumbnailPath: thumbnailPath,
      timestampMs: timestampMs,
      renderTimeMs: renderTimeMs
    )
  }
  func toList() -> [Any?] {
    return [
      thumbnailPath,
      timestampMs,
      renderTimeMs,
    ]
  }
  static func == (lhs: PreviewFrameDto, rhs: PreviewFrameDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DanceApiPigeonInternal.deepEquals(lhs.thumbnailPath, rhs.thumbnailPath) && DanceApiPigeonInternal.deepEquals(lhs.timestampMs, rhs.timestampMs) && DanceApiPigeonInternal.deepEquals(lhs.renderTimeMs, rhs.renderTimeMs)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("PreviewFrameDto")
    DanceApiPigeonInternal.deepHash(value: thumbnailPath, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: timestampMs, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: renderTimeMs, hasher: &hasher)
  }

  public var description: String {
    return "PreviewFrameDto(thumbnailPath: \(String(describing: thumbnailPath)), timestampMs: \(String(describing: timestampMs)), renderTimeMs: \(String(describing: renderTimeMs)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ExportRequestDto: Hashable, CustomStringConvertible {
  var sourceUri: String
  var analysisCacheId: String
  var outputFilePath: String
  var selectedPersonIds: [Int64]
  var effects: EffectConfigDto
  var follow: FollowConfigDto
  var targetWidth: Int64
  var targetHeight: Int64
  var targetFps: Double
  var videoBitrate: Int64
  var processingProfile: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ExportRequestDto? {
    let sourceUri = pigeonVar_list[0] as! String
    let analysisCacheId = pigeonVar_list[1] as! String
    let outputFilePath = pigeonVar_list[2] as! String
    let selectedPersonIds = pigeonVar_list[3] as! [Int64]
    let effects = pigeonVar_list[4] as! EffectConfigDto
    let follow = pigeonVar_list[5] as! FollowConfigDto
    let targetWidth = pigeonVar_list[6] as! Int64
    let targetHeight = pigeonVar_list[7] as! Int64
    let targetFps = pigeonVar_list[8] as! Double
    let videoBitrate = pigeonVar_list[9] as! Int64
    let processingProfile = pigeonVar_list[10] as! String

    return ExportRequestDto(
      sourceUri: sourceUri,
      analysisCacheId: analysisCacheId,
      outputFilePath: outputFilePath,
      selectedPersonIds: selectedPersonIds,
      effects: effects,
      follow: follow,
      targetWidth: targetWidth,
      targetHeight: targetHeight,
      targetFps: targetFps,
      videoBitrate: videoBitrate,
      processingProfile: processingProfile
    )
  }
  func toList() -> [Any?] {
    return [
      sourceUri,
      analysisCacheId,
      outputFilePath,
      selectedPersonIds,
      effects,
      follow,
      targetWidth,
      targetHeight,
      targetFps,
      videoBitrate,
      processingProfile,
    ]
  }
  static func == (lhs: ExportRequestDto, rhs: ExportRequestDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DanceApiPigeonInternal.deepEquals(lhs.sourceUri, rhs.sourceUri) && DanceApiPigeonInternal.deepEquals(lhs.analysisCacheId, rhs.analysisCacheId) && DanceApiPigeonInternal.deepEquals(lhs.outputFilePath, rhs.outputFilePath) && DanceApiPigeonInternal.deepEquals(lhs.selectedPersonIds, rhs.selectedPersonIds) && DanceApiPigeonInternal.deepEquals(lhs.effects, rhs.effects) && DanceApiPigeonInternal.deepEquals(lhs.follow, rhs.follow) && DanceApiPigeonInternal.deepEquals(lhs.targetWidth, rhs.targetWidth) && DanceApiPigeonInternal.deepEquals(lhs.targetHeight, rhs.targetHeight) && DanceApiPigeonInternal.deepEquals(lhs.targetFps, rhs.targetFps) && DanceApiPigeonInternal.deepEquals(lhs.videoBitrate, rhs.videoBitrate) && DanceApiPigeonInternal.deepEquals(lhs.processingProfile, rhs.processingProfile)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ExportRequestDto")
    DanceApiPigeonInternal.deepHash(value: sourceUri, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: analysisCacheId, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: outputFilePath, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: selectedPersonIds, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: effects, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: follow, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: targetWidth, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: targetHeight, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: targetFps, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: videoBitrate, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: processingProfile, hasher: &hasher)
  }

  public var description: String {
    return "ExportRequestDto(sourceUri: \(String(describing: sourceUri)), analysisCacheId: \(String(describing: analysisCacheId)), outputFilePath: \(String(describing: outputFilePath)), selectedPersonIds: \(String(describing: selectedPersonIds)), effects: \(String(describing: effects)), follow: \(String(describing: follow)), targetWidth: \(String(describing: targetWidth)), targetHeight: \(String(describing: targetHeight)), targetFps: \(String(describing: targetFps)), videoBitrate: \(String(describing: videoBitrate)), processingProfile: \(String(describing: processingProfile)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct JobStatusDto: Hashable, CustomStringConvertible {
  var jobId: String
  var state: String
  var currentFrame: Int64
  var totalFrames: Int64
  var fps: Double
  var progress: Double
  var outputUri: String? = nil
  var errorCode: String? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> JobStatusDto? {
    let jobId = pigeonVar_list[0] as! String
    let state = pigeonVar_list[1] as! String
    let currentFrame = pigeonVar_list[2] as! Int64
    let totalFrames = pigeonVar_list[3] as! Int64
    let fps = pigeonVar_list[4] as! Double
    let progress = pigeonVar_list[5] as! Double
    let outputUri: String? = nilOrValue(pigeonVar_list[6])
    let errorCode: String? = nilOrValue(pigeonVar_list[7])
    let errorMessage: String? = nilOrValue(pigeonVar_list[8])

    return JobStatusDto(
      jobId: jobId,
      state: state,
      currentFrame: currentFrame,
      totalFrames: totalFrames,
      fps: fps,
      progress: progress,
      outputUri: outputUri,
      errorCode: errorCode,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      jobId,
      state,
      currentFrame,
      totalFrames,
      fps,
      progress,
      outputUri,
      errorCode,
      errorMessage,
    ]
  }
  static func == (lhs: JobStatusDto, rhs: JobStatusDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return DanceApiPigeonInternal.deepEquals(lhs.jobId, rhs.jobId) && DanceApiPigeonInternal.deepEquals(lhs.state, rhs.state) && DanceApiPigeonInternal.deepEquals(lhs.currentFrame, rhs.currentFrame) && DanceApiPigeonInternal.deepEquals(lhs.totalFrames, rhs.totalFrames) && DanceApiPigeonInternal.deepEquals(lhs.fps, rhs.fps) && DanceApiPigeonInternal.deepEquals(lhs.progress, rhs.progress) && DanceApiPigeonInternal.deepEquals(lhs.outputUri, rhs.outputUri) && DanceApiPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && DanceApiPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("JobStatusDto")
    DanceApiPigeonInternal.deepHash(value: jobId, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: state, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: currentFrame, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: totalFrames, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: fps, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: progress, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: outputUri, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    DanceApiPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
  }

  public var description: String {
    return "JobStatusDto(jobId: \(String(describing: jobId)), state: \(String(describing: state)), currentFrame: \(String(describing: currentFrame)), totalFrames: \(String(describing: totalFrames)), fps: \(String(describing: fps)), progress: \(String(describing: progress)), outputUri: \(String(describing: outputUri)), errorCode: \(String(describing: errorCode)), errorMessage: \(String(describing: errorMessage)))"
  }
}

private class DanceApiPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      return NativeCapabilitiesDto.fromList(self.readValue() as! [Any?])
    case 130:
      return VideoInfoDto.fromList(self.readValue() as! [Any?])
    case 131:
      return DetectedPersonDto.fromList(self.readValue() as! [Any?])
    case 132:
      return AnalyzeRequestDto.fromList(self.readValue() as! [Any?])
    case 133:
      return AnalyzeResultDto.fromList(self.readValue() as! [Any?])
    case 134:
      return EffectConfigDto.fromList(self.readValue() as! [Any?])
    case 135:
      return FollowConfigDto.fromList(self.readValue() as! [Any?])
    case 136:
      return PreviewRequestDto.fromList(self.readValue() as! [Any?])
    case 137:
      return PreviewFrameDto.fromList(self.readValue() as! [Any?])
    case 138:
      return ExportRequestDto.fromList(self.readValue() as! [Any?])
    case 139:
      return JobStatusDto.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class DanceApiPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? NativeCapabilitiesDto {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? VideoInfoDto {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? DetectedPersonDto {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? AnalyzeRequestDto {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? AnalyzeResultDto {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? EffectConfigDto {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? FollowConfigDto {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PreviewRequestDto {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PreviewFrameDto {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? ExportRequestDto {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? JobStatusDto {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class DanceApiPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return DanceApiPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return DanceApiPigeonCodecWriter(data: data)
  }
}

class DanceApiPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = DanceApiPigeonCodec(readerWriter: DanceApiPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol DanceNativeApi {
  func getCapabilities() async throws -> NativeCapabilitiesDto
  func probeVideo(uri: String) async throws -> VideoInfoDto
  func analyzeVideo(request: AnalyzeRequestDto) async throws -> AnalyzeResultDto
  func getPreviewFrame(request: PreviewRequestDto) async throws -> PreviewFrameDto
  func startExport(request: ExportRequestDto) async throws -> String
  func cancelJob(jobId: String) async throws
  func getJobStatus(jobId: String) async throws -> JobStatusDto
  func releaseProject(projectId: String) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class DanceNativeApiSetup {
  static var codec: FlutterStandardMessageCodec { DanceApiPigeonCodec.shared }
  /// Sets up an instance of `DanceNativeApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: DanceNativeApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let getCapabilitiesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dance_native.DanceNativeApi.getCapabilities\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getCapabilitiesChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.getCapabilities()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getCapabilitiesChannel.setMessageHandler(nil)
    }
    let probeVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dance_native.DanceNativeApi.probeVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      probeVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let uriArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.probeVideo(uri: uriArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      probeVideoChannel.setMessageHandler(nil)
    }
    let analyzeVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dance_native.DanceNativeApi.analyzeVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      analyzeVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! AnalyzeRequestDto
        Task { @MainActor in
          do {
            let result = try await api.analyzeVideo(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      analyzeVideoChannel.setMessageHandler(nil)
    }
    let getPreviewFrameChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dance_native.DanceNativeApi.getPreviewFrame\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getPreviewFrameChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PreviewRequestDto
        Task { @MainActor in
          do {
            let result = try await api.getPreviewFrame(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getPreviewFrameChannel.setMessageHandler(nil)
    }
    let startExportChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dance_native.DanceNativeApi.startExport\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      startExportChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ExportRequestDto
        Task { @MainActor in
          do {
            let result = try await api.startExport(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      startExportChannel.setMessageHandler(nil)
    }
    let cancelJobChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dance_native.DanceNativeApi.cancelJob\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelJobChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jobIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.cancelJob(jobId: jobIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      cancelJobChannel.setMessageHandler(nil)
    }
    let getJobStatusChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dance_native.DanceNativeApi.getJobStatus\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getJobStatusChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jobIdArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.getJobStatus(jobId: jobIdArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getJobStatusChannel.setMessageHandler(nil)
    }
    let releaseProjectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.dance_native.DanceNativeApi.releaseProject\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      releaseProjectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let projectIdArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.releaseProject(projectId: projectIdArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      releaseProjectChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol DanceProcessingEventsProtocol {
  func onProgressUpdate(status statusArg: JobStatusDto) async throws
}
class DanceProcessingEvents: DanceProcessingEventsProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: DanceApiPigeonCodec {
    return DanceApiPigeonCodec.shared
  }
  func onProgressUpdate(status statusArg: JobStatusDto) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.dance_native.DanceProcessingEvents.onProgressUpdate\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([statusArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
