// Autogenerated from Pigeon (v28.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.danceanon.native.bridge

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object DanceApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Generated class from Pigeon that represents data sent in messages. */
data class NativeCapabilitiesDto (
  val platform: String,
  val osVersion: String,
  val gpuSupported: Boolean,
  val h264Encoder: Boolean,
  val hevcEncoder: Boolean,
  val maxEncodeWidth: Long,
  val maxEncodeHeight: Long,
  val cpuCores: Long,
  val recommendedProfile: String,
  val supportedProfiles: List<String>,
  val inferenceBackends: List<String>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NativeCapabilitiesDto {
      val platform = pigeonVar_list[0] as String
      val osVersion = pigeonVar_list[1] as String
      val gpuSupported = pigeonVar_list[2] as Boolean
      val h264Encoder = pigeonVar_list[3] as Boolean
      val hevcEncoder = pigeonVar_list[4] as Boolean
      val maxEncodeWidth = pigeonVar_list[5] as Long
      val maxEncodeHeight = pigeonVar_list[6] as Long
      val cpuCores = pigeonVar_list[7] as Long
      val recommendedProfile = pigeonVar_list[8] as String
      val supportedProfiles = pigeonVar_list[9] as List<String>
      val inferenceBackends = pigeonVar_list[10] as List<String>
      return NativeCapabilitiesDto(platform, osVersion, gpuSupported, h264Encoder, hevcEncoder, maxEncodeWidth, maxEncodeHeight, cpuCores, recommendedProfile, supportedProfiles, inferenceBackends)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      platform,
      osVersion,
      gpuSupported,
      h264Encoder,
      hevcEncoder,
      maxEncodeWidth,
      maxEncodeHeight,
      cpuCores,
      recommendedProfile,
      supportedProfiles,
      inferenceBackends,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NativeCapabilitiesDto
    return DanceApiPigeonUtils.deepEquals(this.platform, other.platform) && DanceApiPigeonUtils.deepEquals(this.osVersion, other.osVersion) && DanceApiPigeonUtils.deepEquals(this.gpuSupported, other.gpuSupported) && DanceApiPigeonUtils.deepEquals(this.h264Encoder, other.h264Encoder) && DanceApiPigeonUtils.deepEquals(this.hevcEncoder, other.hevcEncoder) && DanceApiPigeonUtils.deepEquals(this.maxEncodeWidth, other.maxEncodeWidth) && DanceApiPigeonUtils.deepEquals(this.maxEncodeHeight, other.maxEncodeHeight) && DanceApiPigeonUtils.deepEquals(this.cpuCores, other.cpuCores) && DanceApiPigeonUtils.deepEquals(this.recommendedProfile, other.recommendedProfile) && DanceApiPigeonUtils.deepEquals(this.supportedProfiles, other.supportedProfiles) && DanceApiPigeonUtils.deepEquals(this.inferenceBackends, other.inferenceBackends)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.platform)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.osVersion)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.gpuSupported)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.h264Encoder)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.hevcEncoder)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.maxEncodeWidth)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.maxEncodeHeight)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.cpuCores)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.recommendedProfile)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.supportedProfiles)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.inferenceBackends)
    return result
  }
  override fun toString(): String {
    return "NativeCapabilitiesDto(platform=$platform, osVersion=$osVersion, gpuSupported=$gpuSupported, h264Encoder=$h264Encoder, hevcEncoder=$hevcEncoder, maxEncodeWidth=$maxEncodeWidth, maxEncodeHeight=$maxEncodeHeight, cpuCores=$cpuCores, recommendedProfile=$recommendedProfile, supportedProfiles=$supportedProfiles, inferenceBackends=$inferenceBackends)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoInfoDto (
  val codedWidth: Long,
  val codedHeight: Long,
  val displayWidth: Long,
  val displayHeight: Long,
  val fps: Double,
  val durationMs: Long,
  val rotation: Long,
  val videoCodec: String,
  val audioCodec: String? = null,
  val hasAudio: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoInfoDto {
      val codedWidth = pigeonVar_list[0] as Long
      val codedHeight = pigeonVar_list[1] as Long
      val displayWidth = pigeonVar_list[2] as Long
      val displayHeight = pigeonVar_list[3] as Long
      val fps = pigeonVar_list[4] as Double
      val durationMs = pigeonVar_list[5] as Long
      val rotation = pigeonVar_list[6] as Long
      val videoCodec = pigeonVar_list[7] as String
      val audioCodec = pigeonVar_list[8] as String?
      val hasAudio = pigeonVar_list[9] as Boolean
      return VideoInfoDto(codedWidth, codedHeight, displayWidth, displayHeight, fps, durationMs, rotation, videoCodec, audioCodec, hasAudio)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      codedWidth,
      codedHeight,
      displayWidth,
      displayHeight,
      fps,
      durationMs,
      rotation,
      videoCodec,
      audioCodec,
      hasAudio,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoInfoDto
    return DanceApiPigeonUtils.deepEquals(this.codedWidth, other.codedWidth) && DanceApiPigeonUtils.deepEquals(this.codedHeight, other.codedHeight) && DanceApiPigeonUtils.deepEquals(this.displayWidth, other.displayWidth) && DanceApiPigeonUtils.deepEquals(this.displayHeight, other.displayHeight) && DanceApiPigeonUtils.deepEquals(this.fps, other.fps) && DanceApiPigeonUtils.deepEquals(this.durationMs, other.durationMs) && DanceApiPigeonUtils.deepEquals(this.rotation, other.rotation) && DanceApiPigeonUtils.deepEquals(this.videoCodec, other.videoCodec) && DanceApiPigeonUtils.deepEquals(this.audioCodec, other.audioCodec) && DanceApiPigeonUtils.deepEquals(this.hasAudio, other.hasAudio)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.codedWidth)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.codedHeight)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.displayWidth)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.displayHeight)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.fps)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.rotation)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.videoCodec)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.audioCodec)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.hasAudio)
    return result
  }
  override fun toString(): String {
    return "VideoInfoDto(codedWidth=$codedWidth, codedHeight=$codedHeight, displayWidth=$displayWidth, displayHeight=$displayHeight, fps=$fps, durationMs=$durationMs, rotation=$rotation, videoCodec=$videoCodec, audioCodec=$audioCodec, hasAudio=$hasAudio)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class DetectedPersonDto (
  val id: Long,
  val x1: Double,
  val y1: Double,
  val x2: Double,
  val y2: Double,
  val thumbnailPath: String,
  val confidence: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): DetectedPersonDto {
      val id = pigeonVar_list[0] as Long
      val x1 = pigeonVar_list[1] as Double
      val y1 = pigeonVar_list[2] as Double
      val x2 = pigeonVar_list[3] as Double
      val y2 = pigeonVar_list[4] as Double
      val thumbnailPath = pigeonVar_list[5] as String
      val confidence = pigeonVar_list[6] as Double
      return DetectedPersonDto(id, x1, y1, x2, y2, thumbnailPath, confidence)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      id,
      x1,
      y1,
      x2,
      y2,
      thumbnailPath,
      confidence,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as DetectedPersonDto
    return DanceApiPigeonUtils.deepEquals(this.id, other.id) && DanceApiPigeonUtils.deepEquals(this.x1, other.x1) && DanceApiPigeonUtils.deepEquals(this.y1, other.y1) && DanceApiPigeonUtils.deepEquals(this.x2, other.x2) && DanceApiPigeonUtils.deepEquals(this.y2, other.y2) && DanceApiPigeonUtils.deepEquals(this.thumbnailPath, other.thumbnailPath) && DanceApiPigeonUtils.deepEquals(this.confidence, other.confidence)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.id)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.x1)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.y1)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.x2)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.y2)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.thumbnailPath)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.confidence)
    return result
  }
  override fun toString(): String {
    return "DetectedPersonDto(id=$id, x1=$x1, y1=$y1, x2=$x2, y2=$y2, thumbnailPath=$thumbnailPath, confidence=$confidence)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AnalyzeRequestDto (
  val videoUri: String,
  val modelProfile: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AnalyzeRequestDto {
      val videoUri = pigeonVar_list[0] as String
      val modelProfile = pigeonVar_list[1] as String
      return AnalyzeRequestDto(videoUri, modelProfile)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      videoUri,
      modelProfile,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AnalyzeRequestDto
    return DanceApiPigeonUtils.deepEquals(this.videoUri, other.videoUri) && DanceApiPigeonUtils.deepEquals(this.modelProfile, other.modelProfile)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.videoUri)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.modelProfile)
    return result
  }
  override fun toString(): String {
    return "AnalyzeRequestDto(videoUri=$videoUri, modelProfile=$modelProfile)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class AnalyzeResultDto (
  val analysisCacheId: String,
  val videoInfo: VideoInfoDto,
  val persons: List<DetectedPersonDto>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AnalyzeResultDto {
      val analysisCacheId = pigeonVar_list[0] as String
      val videoInfo = pigeonVar_list[1] as VideoInfoDto
      val persons = pigeonVar_list[2] as List<DetectedPersonDto>
      return AnalyzeResultDto(analysisCacheId, videoInfo, persons)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      analysisCacheId,
      videoInfo,
      persons,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AnalyzeResultDto
    return DanceApiPigeonUtils.deepEquals(this.analysisCacheId, other.analysisCacheId) && DanceApiPigeonUtils.deepEquals(this.videoInfo, other.videoInfo) && DanceApiPigeonUtils.deepEquals(this.persons, other.persons)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.analysisCacheId)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.videoInfo)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.persons)
    return result
  }
  override fun toString(): String {
    return "AnalyzeResultDto(analysisCacheId=$analysisCacheId, videoInfo=$videoInfo, persons=$persons)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class EffectConfigDto (
  val fillMode: String,
  val fillColorArgb: Long,
  val borderColorArgb: Long,
  val opacity: Double,
  val borderWidth: Double,
  val blurStrength: Double,
  val faceStickerEnabled: Boolean,
  val stickerAssetId: String? = null,
  val stickerScale: Double,
  val skinWhiten: Double,
  val legStretchEnabled: Boolean,
  val legStretch: Double,
  val legZoneTop: Double,
  val legZoneBottom: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): EffectConfigDto {
      val fillMode = pigeonVar_list[0] as String
      val fillColorArgb = pigeonVar_list[1] as Long
      val borderColorArgb = pigeonVar_list[2] as Long
      val opacity = pigeonVar_list[3] as Double
      val borderWidth = pigeonVar_list[4] as Double
      val blurStrength = pigeonVar_list[5] as Double
      val faceStickerEnabled = pigeonVar_list[6] as Boolean
      val stickerAssetId = pigeonVar_list[7] as String?
      val stickerScale = pigeonVar_list[8] as Double
      val skinWhiten = pigeonVar_list[9] as Double
      val legStretchEnabled = pigeonVar_list[10] as Boolean
      val legStretch = pigeonVar_list[11] as Double
      val legZoneTop = pigeonVar_list[12] as Double
      val legZoneBottom = pigeonVar_list[13] as Double
      return EffectConfigDto(fillMode, fillColorArgb, borderColorArgb, opacity, borderWidth, blurStrength, faceStickerEnabled, stickerAssetId, stickerScale, skinWhiten, legStretchEnabled, legStretch, legZoneTop, legZoneBottom)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      fillMode,
      fillColorArgb,
      borderColorArgb,
      opacity,
      borderWidth,
      blurStrength,
      faceStickerEnabled,
      stickerAssetId,
      stickerScale,
      skinWhiten,
      legStretchEnabled,
      legStretch,
      legZoneTop,
      legZoneBottom,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as EffectConfigDto
    return DanceApiPigeonUtils.deepEquals(this.fillMode, other.fillMode) && DanceApiPigeonUtils.deepEquals(this.fillColorArgb, other.fillColorArgb) && DanceApiPigeonUtils.deepEquals(this.borderColorArgb, other.borderColorArgb) && DanceApiPigeonUtils.deepEquals(this.opacity, other.opacity) && DanceApiPigeonUtils.deepEquals(this.borderWidth, other.borderWidth) && DanceApiPigeonUtils.deepEquals(this.blurStrength, other.blurStrength) && DanceApiPigeonUtils.deepEquals(this.faceStickerEnabled, other.faceStickerEnabled) && DanceApiPigeonUtils.deepEquals(this.stickerAssetId, other.stickerAssetId) && DanceApiPigeonUtils.deepEquals(this.stickerScale, other.stickerScale) && DanceApiPigeonUtils.deepEquals(this.skinWhiten, other.skinWhiten) && DanceApiPigeonUtils.deepEquals(this.legStretchEnabled, other.legStretchEnabled) && DanceApiPigeonUtils.deepEquals(this.legStretch, other.legStretch) && DanceApiPigeonUtils.deepEquals(this.legZoneTop, other.legZoneTop) && DanceApiPigeonUtils.deepEquals(this.legZoneBottom, other.legZoneBottom)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.fillMode)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.fillColorArgb)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.borderColorArgb)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.opacity)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.borderWidth)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.blurStrength)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.faceStickerEnabled)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.stickerAssetId)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.stickerScale)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.skinWhiten)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.legStretchEnabled)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.legStretch)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.legZoneTop)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.legZoneBottom)
    return result
  }
  override fun toString(): String {
    return "EffectConfigDto(fillMode=$fillMode, fillColorArgb=$fillColorArgb, borderColorArgb=$borderColorArgb, opacity=$opacity, borderWidth=$borderWidth, blurStrength=$blurStrength, faceStickerEnabled=$faceStickerEnabled, stickerAssetId=$stickerAssetId, stickerScale=$stickerScale, skinWhiten=$skinWhiten, legStretchEnabled=$legStretchEnabled, legStretch=$legStretch, legZoneTop=$legZoneTop, legZoneBottom=$legZoneBottom)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class FollowConfigDto (
  val enabled: Boolean,
  val targetPersonId: Long? = null,
  val zoom: Double,
  val smoothFactor: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): FollowConfigDto {
      val enabled = pigeonVar_list[0] as Boolean
      val targetPersonId = pigeonVar_list[1] as Long?
      val zoom = pigeonVar_list[2] as Double
      val smoothFactor = pigeonVar_list[3] as Double
      return FollowConfigDto(enabled, targetPersonId, zoom, smoothFactor)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      enabled,
      targetPersonId,
      zoom,
      smoothFactor,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as FollowConfigDto
    return DanceApiPigeonUtils.deepEquals(this.enabled, other.enabled) && DanceApiPigeonUtils.deepEquals(this.targetPersonId, other.targetPersonId) && DanceApiPigeonUtils.deepEquals(this.zoom, other.zoom) && DanceApiPigeonUtils.deepEquals(this.smoothFactor, other.smoothFactor)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.enabled)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.targetPersonId)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.zoom)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.smoothFactor)
    return result
  }
  override fun toString(): String {
    return "FollowConfigDto(enabled=$enabled, targetPersonId=$targetPersonId, zoom=$zoom, smoothFactor=$smoothFactor)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PreviewRequestDto (
  val analysisCacheId: String,
  val timestampMs: Long,
  val selectedPersonIds: List<Long>,
  val effects: EffectConfigDto,
  val follow: FollowConfigDto,
  val faceOnlyPersonIds: List<Long>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PreviewRequestDto {
      val analysisCacheId = pigeonVar_list[0] as String
      val timestampMs = pigeonVar_list[1] as Long
      val selectedPersonIds = pigeonVar_list[2] as List<Long>
      val effects = pigeonVar_list[3] as EffectConfigDto
      val follow = pigeonVar_list[4] as FollowConfigDto
      val faceOnlyPersonIds = pigeonVar_list[5] as List<Long>?
      return PreviewRequestDto(analysisCacheId, timestampMs, selectedPersonIds, effects, follow, faceOnlyPersonIds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      analysisCacheId,
      timestampMs,
      selectedPersonIds,
      effects,
      follow,
      faceOnlyPersonIds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PreviewRequestDto
    return DanceApiPigeonUtils.deepEquals(this.analysisCacheId, other.analysisCacheId) && DanceApiPigeonUtils.deepEquals(this.timestampMs, other.timestampMs) && DanceApiPigeonUtils.deepEquals(this.selectedPersonIds, other.selectedPersonIds) && DanceApiPigeonUtils.deepEquals(this.effects, other.effects) && DanceApiPigeonUtils.deepEquals(this.follow, other.follow) && DanceApiPigeonUtils.deepEquals(this.faceOnlyPersonIds, other.faceOnlyPersonIds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.analysisCacheId)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.timestampMs)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.selectedPersonIds)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.effects)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.follow)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.faceOnlyPersonIds)
    return result
  }
  override fun toString(): String {
    return "PreviewRequestDto(analysisCacheId=$analysisCacheId, timestampMs=$timestampMs, selectedPersonIds=$selectedPersonIds, effects=$effects, follow=$follow, faceOnlyPersonIds=$faceOnlyPersonIds)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PreviewFrameDto (
  val thumbnailPath: String,
  val timestampMs: Long,
  val renderTimeMs: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): PreviewFrameDto {
      val thumbnailPath = pigeonVar_list[0] as String
      val timestampMs = pigeonVar_list[1] as Long
      val renderTimeMs = pigeonVar_list[2] as Double
      return PreviewFrameDto(thumbnailPath, timestampMs, renderTimeMs)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      thumbnailPath,
      timestampMs,
      renderTimeMs,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as PreviewFrameDto
    return DanceApiPigeonUtils.deepEquals(this.thumbnailPath, other.thumbnailPath) && DanceApiPigeonUtils.deepEquals(this.timestampMs, other.timestampMs) && DanceApiPigeonUtils.deepEquals(this.renderTimeMs, other.renderTimeMs)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.thumbnailPath)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.timestampMs)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.renderTimeMs)
    return result
  }
  override fun toString(): String {
    return "PreviewFrameDto(thumbnailPath=$thumbnailPath, timestampMs=$timestampMs, renderTimeMs=$renderTimeMs)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ExportRequestDto (
  val sourceUri: String,
  val analysisCacheId: String,
  val outputFilePath: String,
  val selectedPersonIds: List<Long>,
  val effects: EffectConfigDto,
  val follow: FollowConfigDto,
  val targetWidth: Long,
  val targetHeight: Long,
  val targetFps: Double,
  val videoBitrate: Long,
  val processingProfile: String,
  val enableLivePreview: Boolean,
  val faceOnlyPersonIds: List<Long>? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ExportRequestDto {
      val sourceUri = pigeonVar_list[0] as String
      val analysisCacheId = pigeonVar_list[1] as String
      val outputFilePath = pigeonVar_list[2] as String
      val selectedPersonIds = pigeonVar_list[3] as List<Long>
      val effects = pigeonVar_list[4] as EffectConfigDto
      val follow = pigeonVar_list[5] as FollowConfigDto
      val targetWidth = pigeonVar_list[6] as Long
      val targetHeight = pigeonVar_list[7] as Long
      val targetFps = pigeonVar_list[8] as Double
      val videoBitrate = pigeonVar_list[9] as Long
      val processingProfile = pigeonVar_list[10] as String
      val enableLivePreview = pigeonVar_list[11] as Boolean
      val faceOnlyPersonIds = pigeonVar_list[12] as List<Long>?
      return ExportRequestDto(sourceUri, analysisCacheId, outputFilePath, selectedPersonIds, effects, follow, targetWidth, targetHeight, targetFps, videoBitrate, processingProfile, enableLivePreview, faceOnlyPersonIds)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourceUri,
      analysisCacheId,
      outputFilePath,
      selectedPersonIds,
      effects,
      follow,
      targetWidth,
      targetHeight,
      targetFps,
      videoBitrate,
      processingProfile,
      enableLivePreview,
      faceOnlyPersonIds,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ExportRequestDto
    return DanceApiPigeonUtils.deepEquals(this.sourceUri, other.sourceUri) && DanceApiPigeonUtils.deepEquals(this.analysisCacheId, other.analysisCacheId) && DanceApiPigeonUtils.deepEquals(this.outputFilePath, other.outputFilePath) && DanceApiPigeonUtils.deepEquals(this.selectedPersonIds, other.selectedPersonIds) && DanceApiPigeonUtils.deepEquals(this.effects, other.effects) && DanceApiPigeonUtils.deepEquals(this.follow, other.follow) && DanceApiPigeonUtils.deepEquals(this.targetWidth, other.targetWidth) && DanceApiPigeonUtils.deepEquals(this.targetHeight, other.targetHeight) && DanceApiPigeonUtils.deepEquals(this.targetFps, other.targetFps) && DanceApiPigeonUtils.deepEquals(this.videoBitrate, other.videoBitrate) && DanceApiPigeonUtils.deepEquals(this.processingProfile, other.processingProfile) && DanceApiPigeonUtils.deepEquals(this.enableLivePreview, other.enableLivePreview) && DanceApiPigeonUtils.deepEquals(this.faceOnlyPersonIds, other.faceOnlyPersonIds)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.sourceUri)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.analysisCacheId)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.outputFilePath)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.selectedPersonIds)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.effects)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.follow)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.targetWidth)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.targetHeight)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.targetFps)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.videoBitrate)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.processingProfile)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.enableLivePreview)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.faceOnlyPersonIds)
    return result
  }
  override fun toString(): String {
    return "ExportRequestDto(sourceUri=$sourceUri, analysisCacheId=$analysisCacheId, outputFilePath=$outputFilePath, selectedPersonIds=$selectedPersonIds, effects=$effects, follow=$follow, targetWidth=$targetWidth, targetHeight=$targetHeight, targetFps=$targetFps, videoBitrate=$videoBitrate, processingProfile=$processingProfile, enableLivePreview=$enableLivePreview, faceOnlyPersonIds=$faceOnlyPersonIds)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class JobStatusDto (
  val jobId: String,
  val state: String,
  val currentFrame: Long,
  val totalFrames: Long,
  val fps: Double,
  val progress: Double,
  val outputUri: String? = null,
  val currentPreviewPath: String? = null,
  val errorCode: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): JobStatusDto {
      val jobId = pigeonVar_list[0] as String
      val state = pigeonVar_list[1] as String
      val currentFrame = pigeonVar_list[2] as Long
      val totalFrames = pigeonVar_list[3] as Long
      val fps = pigeonVar_list[4] as Double
      val progress = pigeonVar_list[5] as Double
      val outputUri = pigeonVar_list[6] as String?
      val currentPreviewPath = pigeonVar_list[7] as String?
      val errorCode = pigeonVar_list[8] as String?
      val errorMessage = pigeonVar_list[9] as String?
      return JobStatusDto(jobId, state, currentFrame, totalFrames, fps, progress, outputUri, currentPreviewPath, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      jobId,
      state,
      currentFrame,
      totalFrames,
      fps,
      progress,
      outputUri,
      currentPreviewPath,
      errorCode,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as JobStatusDto
    return DanceApiPigeonUtils.deepEquals(this.jobId, other.jobId) && DanceApiPigeonUtils.deepEquals(this.state, other.state) && DanceApiPigeonUtils.deepEquals(this.currentFrame, other.currentFrame) && DanceApiPigeonUtils.deepEquals(this.totalFrames, other.totalFrames) && DanceApiPigeonUtils.deepEquals(this.fps, other.fps) && DanceApiPigeonUtils.deepEquals(this.progress, other.progress) && DanceApiPigeonUtils.deepEquals(this.outputUri, other.outputUri) && DanceApiPigeonUtils.deepEquals(this.currentPreviewPath, other.currentPreviewPath) && DanceApiPigeonUtils.deepEquals(this.errorCode, other.errorCode) && DanceApiPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.jobId)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.state)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.currentFrame)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.totalFrames)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.fps)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.progress)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.outputUri)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.currentPreviewPath)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + DanceApiPigeonUtils.deepHash(this.errorMessage)
    return result
  }
  override fun toString(): String {
    return "JobStatusDto(jobId=$jobId, state=$state, currentFrame=$currentFrame, totalFrames=$totalFrames, fps=$fps, progress=$progress, outputUri=$outputUri, currentPreviewPath=$currentPreviewPath, errorCode=$errorCode, errorMessage=$errorMessage)"
  }
}
private open class DanceApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NativeCapabilitiesDto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoInfoDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          DetectedPersonDto.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AnalyzeRequestDto.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AnalyzeResultDto.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          EffectConfigDto.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          FollowConfigDto.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PreviewRequestDto.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PreviewFrameDto.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ExportRequestDto.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          JobStatusDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is NativeCapabilitiesDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is VideoInfoDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is DetectedPersonDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is AnalyzeRequestDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is AnalyzeResultDto -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is EffectConfigDto -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is FollowConfigDto -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PreviewRequestDto -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is PreviewFrameDto -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ExportRequestDto -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is JobStatusDto -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface DanceNativeApi {
  suspend fun getCapabilities(): NativeCapabilitiesDto
  suspend fun probeVideo(uri: String): VideoInfoDto
  suspend fun analyzeVideo(request: AnalyzeRequestDto): AnalyzeResultDto
  suspend fun getPreviewFrame(request: PreviewRequestDto): PreviewFrameDto
  suspend fun startExport(request: ExportRequestDto): String
  suspend fun cancelJob(jobId: String)
  suspend fun getJobStatus(jobId: String): JobStatusDto
  suspend fun releaseProject(projectId: String)

  companion object {
    /** The codec used by DanceNativeApi. */
    val codec: MessageCodec<Any?> by lazy {
      DanceApiPigeonCodec()
    }
    /** Sets up an instance of `DanceNativeApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: DanceNativeApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dance_native.DanceNativeApi.getCapabilities$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getCapabilities())
              } catch (exception: Throwable) {
                DanceApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dance_native.DanceNativeApi.probeVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val uriArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.probeVideo(uriArg))
              } catch (exception: Throwable) {
                DanceApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dance_native.DanceNativeApi.analyzeVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as AnalyzeRequestDto
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.analyzeVideo(requestArg))
              } catch (exception: Throwable) {
                DanceApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dance_native.DanceNativeApi.getPreviewFrame$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PreviewRequestDto
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getPreviewFrame(requestArg))
              } catch (exception: Throwable) {
                DanceApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dance_native.DanceNativeApi.startExport$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ExportRequestDto
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.startExport(requestArg))
              } catch (exception: Throwable) {
                DanceApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dance_native.DanceNativeApi.cancelJob$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val jobIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.cancelJob(jobIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                DanceApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dance_native.DanceNativeApi.getJobStatus$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val jobIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getJobStatus(jobIdArg))
              } catch (exception: Throwable) {
                DanceApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.dance_native.DanceNativeApi.releaseProject$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val projectIdArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.releaseProject(projectIdArg)
                listOf(null)
              } catch (exception: Throwable) {
                DanceApiPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class DanceProcessingEvents(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by DanceProcessingEvents. */
    val codec: MessageCodec<Any?> by lazy {
      DanceApiPigeonCodec()
    }
  }
  suspend fun onProgressUpdate(statusArg: JobStatusDto)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.dance_native.DanceProcessingEvents.onProgressUpdate$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(statusArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(DanceApiPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
